# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from python_anticaptcha import AnticaptchaClient, NoCaptchaTaskProxylessTask

def solve_captcha(driver, site_key):
    client = AnticaptchaClient('4a27760ccb2a74b1860b6ff07dd00ab8')
    task = NoCaptchaTaskProxylessTask(site_key, driver.page_source)
    task = NoCaptchaTaskProxylessTask('https://www.komparify.com', site_key)
    job = client.createTask(task)
    job.join()
    return job.get_solution_response()
  

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox(executable_path="C:\geckodriver.exe")
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://www.komparify.com/")
    self.driver.set_window_size(1382, 744)
    self.driver.find_element(By.CSS_SELECTOR, ".signin_acc > img").click()
    self.driver.execute_script("window.scrollTo(0,136)")
    self.driver.find_element(By.ID, "user_email").click()
    self.driver.find_element(By.ID, "user_email").click()
    self.driver.find_element(By.ID, "user_email").send_keys("Sagkrs10@outlook.com")
    self.driver.find_element(By.ID, "home-content-container").click()
    self.driver.find_element(By.ID, "user_password").click()
    self.driver.find_element(By.ID, "user_password").click()
    self.driver.find_element(By.ID, "user_password").send_keys("Sagar28*")
    
    site_key = self.driver.find_element_by_class_name('g-recaptcha').get_attribute('data-sitekey')
    print(site_key)
    response = solve_captcha(self.driver, site_key)
    print("INjecting Response")
    self.driver.execute_script('document.getElementById("g-recaptcha-response").innerHTML = "{}";'.format(response))
    print("Response Injected")
    self.driver.find_element(By.NAME, "commit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".r_bp img").click()
    self.driver.find_element(By.CSS_SELECTOR, "#trans-features p:nth-child(1) img").click()
    self.driver.find_element(By.ID, "recharge_param_number").click()
    self.driver.find_element(By.ID, "recharge_param_number").click()
    self.driver.find_element(By.ID, "recharge_param_number").send_keys("7004969879")
    self.driver.find_element(By.ID, "recharge_param_value").click()
    self.driver.find_element(By.ID, "recharge_param_value").send_keys("11")
    self.driver.find_element(By.CSS_SELECTOR, ".sort-recharge").click()
    self.driver.find_element(By.CSS_SELECTOR, ".amazonpay").click()
    self.driver.find_element(By.ID, "gotopayubutton").click()
    self.driver.find_element(By.ID, "ap_email").click()
    self.driver.find_element(By.ID, "ap_email").send_keys("Rajur2@gatur.online")
    self.driver.find_element(By.ID, "ap_password").click()
    self.driver.find_element(By.ID, "ap_password").send_keys("Sagar6686@")
    self.driver.find_element(By.ID, "signInSubmit").click()
    self.driver.find_element(By.ID, "ap_password").click()
    self.driver.find_element(By.ID, "ap_password").send_keys("Sagar6686@")
    self.driver.find_element(By.ID, "auth-captcha-guess").click()
    self.driver.find_element(By.ID, "auth-captcha-guess").send_keys("6f8c4W")
    self.driver.find_element(By.ID, "signInSubmit").click()
  
test = TestTest1()
test.setup_method("C:\geckodriver.exe")
test.test_test1()